name: Build

on:
  merge_group:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install tree-sitter CLI
        uses: tree-sitter/setup-action@v2
        with:
          tree-sitter-ref: v0.25.4

      - name: Generate tree-sitter grammar
        run: tree-sitter generate

      - name: Commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -a -m "build: bump artifacts [skip ci]"
            git push origin HEAD:main
          fi
