name: Fuzz

on:
  push:
    branches: ["main"]
    paths:
      - src/scanner.c
  pull_request:
    paths:
      - src/scanner.c

jobs:
  fuzz:
    name: fuzz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install tree-sitter CLI
        uses: tree-sitter/setup-action@v2
        with:
          tree-sitter-ref: v0.25.4

      - name: Generate tree-sitter grammar
        run: tree-sitter generate

      - name: Run fuzz tests
        uses: tree-sitter/fuzz-action@v4
        with:
          corpus: test/corpus
