name: Fuzz

on:
  push:
    branches: [ "main" ]
    paths:
      - src/scanner.c
  pull_request:
    paths:
      - src/scanner.c

jobs:
  fuzz:
    name: fuzz
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: tree-sitter/fuzz-action@v4
        with:
          corpus: test/corpus
