name: Test MBTQ

on:
  push:
    branches: ["main"]
    paths:
      - mbtq/grammar.js
      - mbtq/src/**
      - mbtq/bindings/**
      - mbtq/binding.gyp
  pull_request:
    paths:
      - mbtq/grammar.js
      - mbtq/src/**
      - mbtq/bindings/**
      - mbtq/binding.gyp

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup tree-sitter
        uses: tree-sitter/setup-action/cli@v2
        with:
          tree-sitter-ref: v0.25.4

      - name: Generate tree-sitter parser
        working-directory: mbtq
        run: tree-sitter generate

      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          generate: false
          test-parser-cmd: (cd mbtq && tree-sitter test)
