name: Test

on:
  push:
    branches: ["main"]
    paths:
      - grammar.js
      - src/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - grammar.js
      - src/**
      - bindings/**
      - binding.gyp

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup tree-sitter
        uses: tree-sitter/setup-action/cli@v2
        with:
          tree-sitter-ref: v0.25.4

      - name: Generate tree-sitter parser
        run: python3 scripts/generate.py

      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          generate: false

  test-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup tree-sitter
        uses: tree-sitter/setup-action/cli@v2
        with:
          tree-sitter-ref: v0.25.4

      - name: Generate tree-sitter parser
        run: python3 scripts/generate.py

      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          generate: false
          test-parser: false
          test-go: true

  test-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup tree-sitter
        uses: tree-sitter/setup-action/cli@v2
        with:
          tree-sitter-ref: v0.25.4

      - name: Generate tree-sitter parser
        run: python3 scripts/generate.py

      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          generate: false
          test-parser: false
          test-rust: true

  test-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup tree-sitter
        uses: tree-sitter/setup-action/cli@v2
        with:
          tree-sitter-ref: v0.25.4

      - name: Generate tree-sitter parser
        run: python3 scripts/generate.py

      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          generate: false
          test-parser: false
          test-python: true

  test-node:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup tree-sitter
        uses: tree-sitter/setup-action/cli@v2
        with:
          tree-sitter-ref: v0.25.4

      - name: Generate tree-sitter parser
        run: python3 scripts/generate.py

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "npm"

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  test-core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup tree-sitter
        uses: tree-sitter/setup-action/cli@v2
        with:
          tree-sitter-ref: v0.25.4

      - name: Generate tree-sitter parser
        run: python3 scripts/generate.py

      - name: Checkout moonbitlang/core
        run: git clone https://github.com/moonbitlang/core.git

      - name: Test core
        id: core
        uses: tree-sitter/parse-action@v4
        with:
          files: core/**/*.mbt

      - name: Upload failures
        uses: actions/upload-artifact@v4
        if: ${{ always() && steps.core.outputs.failures != '' }}
        with:
          name: failures
          path: ${{steps.core.outputs.failures}}
