name: Test

on:
  push:
    branches: ["main"]
    paths:
      - grammar.js
      - src/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - grammar.js
      - src/**
      - bindings/**
      - binding.gyp

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup tree-sitter
        uses: tree-sitter/setup-action/cli@v2
        with:
          tree-sitter-ref: v0.25.4

      - name: Generate tree-sitter parser
        run: tree-sitter generate

      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          test-rust: true
          test-node: true
          test-python: true
          test-go: true
          test-swift: true

  test-core:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup tree-sitter
        uses: tree-sitter/setup-action/cli@v2
        with:
          tree-sitter-ref: v0.25.4

      - name: Generate tree-sitter parser
        run: tree-sitter generate

      - name: Checkout moonbitlang/core
        run: git clone https://github.com/moonbitlang/core.git

      - name: Test core
        id: core
        uses: tree-sitter/parse-action@v4
        with:
          files: core/**/*.mbt

      - name: Upload failures
        uses: actions/upload-artifact@v4
        if: ${{ always() && steps.core.outputs.failures != '' }}
        with:
          name: failures
          path: ${{steps.core.outputs.failures}}
